http:
  middlewares:
    common-auth:
      basicAuth:
        usersFile: "/etc/traefik/http_auth"
    security-headers:
      headers:
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000

        referrerPolicy: "same-origin"
        featurePolicy: "vibrate 'self'; geolocation 'self'; midi 'self'; notifications 'self'; push 'self'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'self'; fullscreen 'self'"

        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: false
    authelia:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=https://sso.{{ env "TRAEFIK_DOMAIN" }}
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
    chain-authelia:
      chain:
        middlewares:
          - security-headers
          - authelia
