services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - PASSWORD=${CALIBRE_PASSWORD}
      - CLI_ARGS=
    volumes:
      - configcalibre:/config

  calibre-web:
    image: hcr.io/linuxserver/calibre-web
    container_name: calibre-web
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - configcalibre:/config

volumes:
  configcalibre: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/calibre