services:
  mariadb:
      image: mariadb:10
      container_name: mariadb
      command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
      user: ${PUID}:${PGID}
      restart: always
      environment:
        - TZ=${TZ}
      volumes: 
        - nextclouddb:/var/lib/mysql
      labels:
        - "traefik.enable=false"

volumes:
  nextclouddb:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/nextcloud-db