services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: always
    network_mode: host
    devices:
      - /dev/dri:/dev/dri # for hardware transcoding
    volumes:
      - configplex:/config
      - torrents:/torrents
      - /dev/shm:/transcode
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - VERSION=latest

volumes:
  configplex:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/Plex